# Generated by Django 5.2.14 on 2026-05-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('airports', models.ManyToManyField(related_name='airlines', to='location.airport')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='location.country')),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=15, unique=True)),
                ('manufactured_year', models.PositiveIntegerField()),
                ('num_of_passengers', models.PositiveIntegerField()),
                ('crew_count', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='airline.airline')),
                ('airplane_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='airline.airplanetype')),
            ],
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first', 'First')], max_length=30)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('baggage_kg', models.PositiveIntegerField(default=0)),
                ('priority_boarding', models.BooleanField(default=False)),
                ('lounge_access', models.BooleanField(default=False)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_classes', to='airline.airline')),
            ],
            options={
                'unique_together': {('airline', 'class_type')},
            },
        ),
        migrations.CreateModel(
            name='AirplaneSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('seat_letter', models.CharField(max_length=1)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('is_exit_row', models.BooleanField(default=False)),
                ('has_extra_legroom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='airline.airplane')),
                ('seat_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='airplane_seats', to='airline.seatclass')),
            ],
            options={
                'unique_together': {('airplane', 'row_number', 'seat_letter')},
            },
        ),
    ]
