# Generated by Django 5.2.14 on 2026-05-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iata_code', models.CharField(max_length=3, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('airports', models.ManyToManyField(related_name='airlines', to='location.airport')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlines', to='location.country')),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tail_number', models.CharField(max_length=15, unique=True)),
                ('manufactured_year', models.PositiveIntegerField()),
                ('num_of_passengers', models.PositiveIntegerField()),
                ('crew_count', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='airline.airline')),
                ('airplane_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplanes', to='airline.airplanetype')),
            ],
        ),
    ]
