# Generated by Django 5.2.14 on 2026-06-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='airplaneseat',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seatclass',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='airplaneseat',
            name='seat_letter',
            field=models.CharField(max_length=3),
        ),
        migrations.AddConstraint(
            model_name='airplaneseat',
            constraint=models.UniqueConstraint(fields=('airplane', 'row_number', 'seat_letter'), name='unique_seat_per_airplane'),
        ),
        migrations.AddConstraint(
            model_name='seatclass',
            constraint=models.UniqueConstraint(fields=('airline', 'class_type'), name='unique_seat_class_per_airline'),
        ),
    ]
