# Generated by Django 5.2.14 on 2026-05-30 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flightseat',
            name='pending_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='flightseat',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='flightseat',
            name='pending_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_flight_seats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flightseat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold'), ('blocked', 'Blocked')], default='available', max_length=20),
        ),
    ]
