# Generated by Django 5.2.14 on 2026-06-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0003_rename_reserved_until_flightseat_held_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightseat',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('paid', 'Paid'), ('blocked', 'Blocked')], default='available', max_length=20),
        ),
    ]
