# Generated by Django 5.2.14 on 2026-06-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0005_fix_missing_flightseat_pending_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightseat',
            name='reserved_until',
        ),
    ]
