# Generated by Django 5.2.14 on 2026-06-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0006_remove_flightseat_reserved_until'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flightseat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='flightseat',
            name='airplane_seat',
        ),
        migrations.RemoveField(
            model_name='flightseat',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='flightseat',
            name='pending_by',
        ),
    ]
