# Generated by Django 5.2.14 on 2026-06-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0007_alter_flightseat_unique_together_and_more'),
        ('ticket', '0004_remove_ticket_flight_seat_ticket_airplane_seat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlightSeat',
        ),
    ]
