# Generated by Django 5.2.14 on 2026-05-10 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('ticket', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.CharField(blank=True, max_length=150)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounges', to='location.airport')),
            ],
        ),
        migrations.CreateModel(
            name='LoungeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('business_class', 'Business Class'), ('loyalty_program', 'Loyalty Program'), ('bank_card', 'Bank Card'), ('paid_access', 'Paid Access')], max_length=30)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='lounge.lounge')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lounge_accesses', to='ticket.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounge_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
