# Generated by Django 5.2.14 on 2026-05-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_description', models.CharField(blank=True, max_length=150)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('access_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounges', to='location.airport')),
            ],
        ),
        migrations.CreateModel(
            name='LoungeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('business_class', 'Business Class'), ('loyalty_program', 'Loyalty Program'), ('bank_card', 'Bank Card'), ('paid_access', 'Paid Access')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='lounge.lounge')),
            ],
        ),
    ]
