# Generated by Django 5.2.14 on 2026-05-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('passenger', 'Passenger'), ('support', 'Support'), ('manager', 'Manager')], default='passenger', max_length=20),
        ),
    ]
