# Generated by Django 5.2.14 on 2026-05-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], max_length=20, unique=True)),
                ('baggage_kg', models.PositiveIntegerField()),
                ('priority_boarding', models.BooleanField(default=False)),
                ('lounge_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='created', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_first_name', models.CharField(max_length=100)),
                ('passenger_last_name', models.CharField(max_length=100)),
                ('seat_number', models.CharField(blank=True, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('paid', 'Paid'), ('used', 'Used'), ('cancelled', 'Cancelled')], default='booked', max_length=20)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flight.flight')),
                ('ticket_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.ticketclass')),
            ],
        ),
    ]
