# Generated by Django 5.2.14 on 2026-05-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
