# Generated by Django 5.2.14 on 2026-06-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_alter_airplaneseat_unique_together_and_more'),
        ('flight', '0007_alter_flightseat_unique_together_and_more'),
        ('ticket', '0003_alter_booking_status_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='flight_seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='airplane_seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='airline.airplaneseat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flight.flight'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'paid'])), fields=('flight', 'airplane_seat'), name='unique_active_ticket_per_flight_seat'),
        ),
    ]
