# Generated by Django 5.2.14 on 2026-05-19 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketclass_extra_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='extra_price',
        ),
    ]
